from itertools import product
from weight_calculator import pauli_weight, minimum_pauli_weight
from collections import Counter

generators = [
    "XZIIZZ",
    "ZXZZII",
    "IZXZIZ",
    "IZZXZI",
    "ZIIZXZ",
    "ZIZIZX",
]

# multiplying two Pauli strings
def multiply_paulis(pauli_a: str, pauli_b: str) -> str:
    pauli_products = {("X","Z"): "Y",
                      ("Z","X"): "Y",
                      ("Z","Z"): "I",
                      ("X","X"): "I",
                      ("Y","Y"): "I",
                      ("X","Y"): "Z",
                      ("Y","X"): "Z",
                      ("Y","Z"): "X",
                      ("Z","Y"): "X",
                      ("Z","I"): "Z",
                      ("X","I"): "X",
                      ("Y","I"): "Y",
                      ("I","X"): "X",
                      ("I","Y"): "Y",
                      ("I","Z"): "Z",
                      ("I","I"): "I",}

    if not pauli_a or not pauli_b:
        raise ValueError("The Pauli string cannot be empty.")

    if len(pauli_a) != len(pauli_b):
        raise ValueError("The Pauli strings must have the same length.")

    return "".join(pauli_products[(symbol_a, symbol_b)] for symbol_a, symbol_b in zip(pauli_a, pauli_b))

# build the power sets at length 6 consisting og 0 and 1
def generate_powers(number_of_generators: int):
    return list(product([0, 1], repeat=number_of_generators))

# building of power of generators
def power_of_generator(power: int, generator: str) -> str:
    if power==0:
        return "I"*len(generator)
    return generator

# multiplying six generators
def multiply_generators(pauli_strings: list[str]) -> str:
    result = "I" * len(pauli_strings[0])

    for pauli_string in pauli_strings:
        result = multiply_paulis(result, pauli_string)

    return result


# create all Pauli stabilizers from the six generators
def create_all_stabilizers(generators: list[str]) -> list[str]:
    all_stabilizers = []

    power_vector = generate_powers(len(generators))

    for power_set in power_vector:
        pauli_strings = [power_of_generator(power, generator) for power, generator in zip(power_set, generators)]
        product_strings = multiply_generators(pauli_strings)

        all_stabilizers.append(product_strings)


    return all_stabilizers

if __name__ == '__main__':
    print(f"All of 2^6=64 stabilizers generated by the six generators are as follows:")
    for stabilizer in create_all_stabilizers(generators):
        print(f"{stabilizer} the weight: {pauli_weight(stabilizer)}")

    weight_distribution = Counter(pauli_weight(stabilizer) for stabilizer in create_all_stabilizers(generators))

    print("Weight distribution:")

    for weight in sorted(weight_distribution):
        print(f"Weight {weight}: {weight_distribution[weight]} stabilizers")

    all_stabilizers = create_all_stabilizers(generators)
    all_stabilizers.remove("I"*len(generators[0]))
    print("Minimum non-identity stabilizer weight:", minimum_pauli_weight(all_stabilizers))